# Configuration for DelayedStop
#   - ddj 2011
#

### Notification settings
#   Here you can setup at what intervals in the countdown, you would like
#   to inform your players on the upcoming server shutdown/restart
#   Use <number>m to use minutes, 
#   Use <number> or <number>s to use seconds
#   ALWAYS setup this values from high to low otherwise it will not work as expected!!
notification:
    notify-at: 10m,5m,1m,30s,10s
### Labels ###
labelsandcolors:
    chat-prefix: '[DS]'
    chat-prefix-color: '&d'
    chat-message-color: '&e'
    chat-highlighted-color: '&a'
    ### Broadcast messages  ###
broadcasttext:
    time-left-message: 'The server will restart in @time-left@'
    restart-cancelled-message: 'Server restart is cancelled!'
    server-down-message: 'Server is shutting down!'
    restart-resumed-message: 'Server restart is resumed'
    restart-paused-message: 'Server restart is paused'
    minute-text: 'minutes'
    second-text: 'seconds'
    minutes-text: 'minutes'
    seconds-text: 'seconds'
    and-text: 'and'
    
    
