name: DelayedStop
main: nl.crafters.delayedstop.DelayedStop
version: 0.12
authors:
- ddj
commands:
    dstop:
        description: Stops server after x seconds
        usage: /<command> [seconds|cancel] <reason>
